### ISSUE TITLE
Add Ars Magica 2 with disabled components

### ISSUE THREAD

**Issue by LuminaDragon** [kayila/minecraftmodpacks#10]
Please add Ars Magica 2 (I <3 my ultility spells) with the following disabled for balance:

Chrono Anchor - component
Damage - modifier
Duration - modifier
Piercing - modifier
Gravity - modifier

Firestorm - component
Blizzard - component
Starstrike - component

**Comment by MechaMaria64** [comment]
those are the op as hell components and modifiers. id be okay with that

**Comment by LuminaDragon** [comment]
yeah exactly :)  I'm totally ok without one shotting bosses.
