### ISSUE TITLE
Project Red and Control panels

### ISSUE THREAD

**Issue by MechaMaria64** [kayila/minecraftmodpacks#15]
Project Red would allow for advanced redstone control over automation. and then this mod, hexis, would allow us to make the systems and controls for the automation circuits super compact! http://www.google.com/url?q=http%3A%2F%2Fminecraft.curseforge.com%2Fprojects%2Fhexis-functional-decoration&sa=D&sntz=1&usg=AFQjCNGqA0JCromdTeVbCwDW3TKnJtjAQQ

**Comment by kayila** [comment]
http://minecraft.curseforge.com/projects/hexis-functional-decoration

**Comment by MechaMaria64** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290357-forge-multipart-projectred-v4-7-0pre10-93-01-07

**Comment by kayila** [comment]
I need more details, @256spam......  What parts of Project Red do you want? Modules include Core, Integration, Transmission, Expansion, Transportation, Exploration, Illumination, and Compatability...

**Comment by MechaMaria64** [comment]
Core, intergration, transmission, expansion, illumination and compatability.

I dont like project red's worldgen, so no explore. and its item transport is very iffy... so id not really like it

**Comment by kayila** [comment]
Sadly the control panels (hexis functional decorations) were crashing the pack as soon as a control panel was placed....

That being said however, Project Red now seems to include a button panel....
