### ISSUE TITLE
Add Backpacks mod

### ISSUE THREAD

**Issue by LuminaDragon** [kayila/minecraftmodpacks#30]
Please and thank you

**Comment by kayila** [comment]
Which one? There are several...

**Comment by LuminaDragon** [comment]
The one called "Backpacks" not the buggy one as cool as the ender dragon backpack was.  :)

**Comment by kayila** [comment]
I think I may have found a cooler backpack mod.....

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291844-backpacks-by-brad16840
