### ISSUE TITLE
Add mekanism

### ISSUE THREAD

**Issue by MechaMaria64** [kayila/minecraftmodpacks#5]

**Comment by kayila** [comment]
So do you propose disabling other forms of RF generation in mekanism? _devil's advocate_

**Comment by MechaMaria64** [comment]
Yeah. although i barely touch those anyways. not useful reeally.

**Comment by MechaMaria64** [comment]
storage should remain tghough

**Comment by kayila** [comment]
Interesting... I'll think about removing the generators, but mekanism can definately go in.

**Comment by kayila** [comment]
Mekanism doesn't have the means to produce power from steam. This is asking to disable all forms of power generation added by this mod.

**Comment by MechaMaria64** [comment]
yeah. we have railcraft

**Comment by kayila** [comment]
Decided to keep the RF generators, you can just not use them if you'd like.
