### ISSUE TITLE
Suggested Mods for New 1.8.9 Pack

### ISSUE THREAD

**Issue by LuminaDragon** [kayila/minecraftmodpacks#53]
----Server Utility----
Wawla
Enchiridion
Voxel Map
Morpheus
World Edit
More Player Models
NetherPortalFix
Pam's HarvestCraft
Stackable Potions
JEIAddons
JustEnoughTooltips

---Utility Items----
Iron Chests
Chest Transporter
Warp Book
Similsax Transtructors
WholeTreeAxe
Simple Fluid Tanks
Bagginses

----Cosmetic Items----
ArchitectureCraft
Horizontal Glass Panes
Immersive Craft
Malisis Doors
Malisis Switches
Bed Craft and Beyond
Staircraft

----Magic----
Basic Elements
Thaumcraft (and expansions)
Botania (Unofficial)
Potion Core
Not Enough Potions

----Tech----
Quantum Flux
Tinkers Construct
Redstone Paste
Hydraulicraft
Steam Engines Mod
OpenComputers

**Comment by kayila** [comment]
Also want to add:
- Custom NPCs
- Chisels and bits
- Deathwatch
- Fast Leaf Decay
- rftools/dimensions

**Comment by MechaMaria64** [comment]
looks good to me

**Comment by MechaMaria64** [comment]
Wait! almost forgot! can we have buildcraft and Ic2?

**Comment by LuminaDragon** [comment]
http://minecraftsix.com/tails-mod/  :D
