### ISSUE TITLE
Add mystcraft

### ISSUE THREAD

**Issue by kayila** [kayila/minecraftmodpacks#9]

**Comment by 256spam** [comment]
id prefer not... being able to make specially locked away dimensions is kind of overpowered. for the same reason id prefer no dimensional doors too

**Comment by MechaMaria64** [comment]
Only if we get dimensional doors too.

**Comment by kayila** [comment]
Why? dim doors clutters up worldgen like nuts with it's dungeons.

**Comment by MechaMaria64** [comment]
Because i wanna put storage in a dimensional door. 

Cause im like that.

So, yeah =P

**Comment by kayila** [comment]
Witchery mirrors suitable? I really don't want the worldgen clutter if it can be avoided, but if I turn off spawning the dungeons than you can't get the mats to make the doors.... Really you should be opening a new issue for this, btw....

**Comment by MechaMaria64** [comment]
they are too small...
